### ISSUE TITLE
Q: How do I run ops on a cloud provider with bridged networking?

### ISSUE THREAD

**Issue by prologic** [nanovms/ops-documentation#69]
Hi! Currently the FAQ over at [docs](https://nanovms.gitbook.io/ops/faq) states for tollowing for the above question:

> A: We do not suggest running ops on a cloud provider on top of linux. We suggest using the native way of provisioning your unikernels so they run by themselves standalone and you won't have do any network configuration.

I'm a little unclear on this part:

> We suggest using the native way of provisioning your unikernels so they run by themselves standalone and you won't have do any network configuration.

What is meant by "native" here?

Run standalone where/how?

Can you elaboarate on this a bit more in general to be more specific with AWS/EC2 and ops?

**Comment by eyberg** [comment]
sorry - just now seeing this we have a public email list available at nanos-users@nanovms.com btw

as for this specific question - this is a short tutorial on deploying a node app to aws 'natively' (eg: the unikernel as an ami - not on top of linux)

https://nanovms.com/dev/tutorials/deploying-nanos-node-js-unikernels-to-aws

does this make sense?

**Comment by prologic** [comment]
Ahh very nice. I read the tutorials its basically just all nicely integrated into the `ops` tool. That's awesome for AWS and other supported platforms. My question was a bit more technical I suppose -- I saw nothing about any of the internals of the nanoos kernel for example and how it deals with bridged networking? For example if I were to start deploying nanovm(s) to my own infra where the Hypervisor is Proxmox VE (KVM/QEMU) how would this work?

**Comment by prologic** [comment]
Or more precisely; I can boot the disk image just fine. Is there anything special I need to do do make networking work?

**Comment by eyberg** [comment]
maybe I'm misunderstanding  but if you are on a public cloud (eg: google cloud or aws) kvm won't work w/out the virtualization extensions and as afaik the only option avail is gcloud nested virtualization (and there will be a perf tax for that regardless) - otherwise you straight up don't have virtualization options on other types of instances - also if you are going to bridge on a public interface for pass-through traffic you'll prob want 2 interfaces (one for ssh) or you won't bridge on the public interface and use iptables to forward traffic instead - essentially it's not really a use-case - best just to use the underlying virtualization the cloud gives you to begin with

now - if on the other hand ..

you're trying to build your own non-public cloud platform using kvm or proxmox (eg: your own bare metal server via hetzner or packet.net or maybe you have a rack somewhere) than you can use ops' built-in networking options which is a loose abstraction over this -> https://github.com/nanovms/nanos/blob/master/networking_setup - the bridge itself in this case is external to nanos and nanos doesn't care if it's static or dynamic - that's outside it's worldview

**Comment by prologic** [comment]
Thanks :D That makes much more sense now; to be honest I'm not even sure why the FAQ entry exists because as you rightly point out the NanoVM(s) themselves don't really care what their "NIC"(s) are plugged into to. It's more of a Hypervisor FAQ I guess; Can I use Bridged networking with Public Cloud X or Hypervisor X (e.g: qemu, VirtualBox, etc). Sorry for the confusion but I couldn't at first understand why networking would be so special with a nanovm :)

On that note; I'll close this issue; if you want to amend that FAQ entry a bit cool! But I will by playing with nanovms and ops on a Proxmox VE environment (yes on a Rack with some gear in it)

**Comment by eyberg** [comment]
networking's def. not special; there's just no reason to deploy these on top of a public cloud linux vm - if you want to use public cloud the preferred way is to deploy them as their own amis or cloud images not on top of linux vms..

if you want to have more control on the orchestration side of things at the hypervisor level - you'll want that to be on real metal as to avoid the  nested virtualization tax - feel free to open up a PR if you clarify the language

**Comment by prologic** [comment]
I'll have a think about it and re-read the docs. If I can come up with better language I'll put up said PR. Thanks for the clarification!

**Comment by cdosoftei** [comment]
For the networking aspect, any build post-https://github.com/nanovms/nanos/commit/6fa5f372ddde92847a7ba981a1d91e67717bd2bd should sort out the networking issues on PVE (it prefers upper PCI slots for the NIC, and they were not considered prior).
